import type { IncomingMessage } from 'http';
import type { Duplex } from 'stream';
import { WebSocketServer, type WebSocket } from 'ws';
import { MAX_FRAME_SIZE_BYTES, decodeBinaryFrame, decodeJsonFrame, wsDataToBuffer, wsDataToString } from '../pilot/protocol';
import {
    TcpStreamSwitchboard,
    attachTcpStreamSwitchboard,
    resolveByComposeLabels,
    type ReverseTcpStreamHandle,
} from '../mesh/tcpStreamSwitchboard';
import { sanitizeForLog } from '../utils/safeLog';
import { isDebugEnabled } from '../utils/debug';
import { rejectUpgrade as reject } from './reject';
import { MeshCentralRegistry, type MeshCentralMaterial } from '../services/MeshCentralRegistry';

/**
 * Bootstrap phase for the first-frame state machine.
 *
 * Central MAY send a `mesh_handshake` JSON frame as the FIRST text frame
 * after upgrade. If it arrives we persist the callback material via
 * MeshCentralRegistry and transition to `consumed`. Any frame other than
 * the handshake (or no frame at all) moves us to `past`, after which a
 * later handshake is a protocol error.
 */
type BootstrapPhase = 'awaiting' | 'consumed' | 'past';

interface MeshHandshakeFrame {
    t: 'mesh_handshake';
    v: number;
    peerNodeId: number;
    centralInstanceId: string;
    centralApiUrl: string;
    meshTunnelJwt: string;
    jwtExpiresAt: number;
}

function isMeshHandshakeFrame(parsed: unknown): parsed is MeshHandshakeFrame {
    return typeof parsed === 'object' && parsed !== null
        && (parsed as { t?: unknown }).t === 'mesh_handshake'
        && typeof (parsed as { v?: unknown }).v === 'number'
        && typeof (parsed as { peerNodeId?: unknown }).peerNodeId === 'number'
        && typeof (parsed as { centralInstanceId?: unknown }).centralInstanceId === 'string'
        && typeof (parsed as { centralApiUrl?: unknown }).centralApiUrl === 'string'
        && typeof (parsed as { meshTunnelJwt?: unknown }).meshTunnelJwt === 'string'
        && typeof (parsed as { jwtExpiresAt?: unknown }).jwtExpiresAt === 'number';
}

/**
 * Mesh proxy-tunnel ingress.
 *
 * The remote side of a Phase C proxy-mode mesh tunnel. Central dials
 * `WSS <api_url>/api/mesh/proxy-tunnel` using the fleet credential as a
 * Bearer header (either the `node_proxy` JWT generated by the remote's
 * Settings → Nodes → Generate Token flow, or a `full-admin` api_token
 * for non-fleet integrations); this handler upgrades the connection and
 * wires the shared `TcpStreamSwitchboard` to handle `tcp_open` /
 * `tcp_open_ack` / `tcp_open_reverse` / `tcp_close` and `TcpData` frames.
 *
 * Auth + scope gating happens in `upgradeHandler.ts` before this handler
 * runs: it accepts node_proxy and full-admin api_token, and rejects
 * session cookies plus restricted api_token scopes. The handler itself
 * trusts the upgrade; the WS credential is the only trust boundary.
 *
 * Bidirectional: when the tunnel opens, the handler registers itself as
 * the reverse-dialer on the local MeshService so meshed containers on
 * this Sencho can dial cross-node aliases via `tcp_open_reverse` over
 * the same WS. On disconnect the reverse-dialer registration is
 * cleared.
 */
const wss = new WebSocketServer({ noServer: true, maxPayload: MAX_FRAME_SIZE_BYTES });

/**
 * Upper bound on the pre-CAS first-frame wait inside attachSwitchboard.
 * Sized to cover localhost-loopback RTT plus a slim margin for the
 * central-side ms-scale gap between `ws.send(mesh_handshake)` and the
 * registerProxyBridge throw + ws.close that follows on a refused dial.
 * On a dial that carries no bootstrap, this is pure added latency
 * before the reverse-dialer install; 30ms is well below operator
 * perception and well above realistic localhost RTT.
 */
const FIRST_FRAME_WAIT_MS = 30;

interface SwitchboardReverseDialer {
    openMeshTcpStream(target: { nodeId: number; stack: string; service: string; port: number }): ReverseTcpStreamHandle | null;
}

export async function handleMeshProxyTunnel(req: IncomingMessage, socket: Duplex, head: Buffer): Promise<void> {
    // Mesh service is only available on the central deployment (SENCHO_MODE
    // unset or 'central'). Pilot-mode Sencho receives mesh traffic via the
    // pilot tunnel and has no use for the proxy-mode WS path.
    if (process.env.SENCHO_MODE === 'pilot') {
        return reject(socket, 404, 'Not Found');
    }

    // Central appends `?nodeId=<central-namespace-id>` so this peer can tag
    // its own MeshService with the right nodeId for `handleAccept` dispatch.
    // The value is unsigned, but the Bearer credential at the upgrade has
    // already proven the caller is the upstream central (auth + scope gate
    // in `upgradeHandler.ts`); the query param's trust ceiling is the
    // token's trust ceiling.
    // Strict regex (no parseInt) so `?nodeId=14.5`, `?nodeId=00014`,
    // `?nodeId=1e2`, leading whitespace, etc. are rejected rather than
    // silently truncated.
    let peerNodeId: number | null = null;
    try {
        const parsed = new URL(req.url ?? '/', `http://${req.headers.host || 'localhost'}`);
        const raw = parsed.searchParams.get('nodeId');
        if (raw != null && /^[1-9][0-9]*$/.test(raw)) {
            const n = Number(raw);
            if (Number.isSafeInteger(n)) peerNodeId = n;
        }
    } catch {
        // Malformed URL; treat as missing param.
    }
    if (peerNodeId === null) {
        console.warn('[MeshProxy] proxy-tunnel upgrade missing or malformed nodeId query param; reverse-direction mesh dispatch will be undefined until central upgrades');
    }

    await new Promise<void>((resolve) => {
        wss.handleUpgrade(req, socket as Parameters<typeof wss.handleUpgrade>[1], head, (ws) => {
            void attachSwitchboard(ws, peerNodeId).finally(resolve);
        });
    });
}

async function attachSwitchboard(ws: WebSocket, peerNodeId: number | null): Promise<void> {
    let switchboard: TcpStreamSwitchboard | null = null;
    let meshServiceCleanup: (() => void) | null = null;
    let phase: BootstrapPhase = 'awaiting';

    const onMessage = (data: unknown, isBinary: boolean): void => {
        if (!switchboard) return;
        try {
            if (isBinary) {
                if (phase === 'awaiting') phase = 'past';
                const buf = wsDataToBuffer(data);
                if (!buf) return;
                switchboard.handleBinaryFrame(decodeBinaryFrame(buf));
                return;
            }
            const text = wsDataToString(data);
            if (text == null) {
                if (phase === 'awaiting') phase = 'past';
                return;
            }
            let parsedForBootstrap: unknown = null;
            let parseSucceeded = false;
            try {
                parsedForBootstrap = JSON.parse(text);
                parseSucceeded = true;
            } catch {
                // Not valid JSON; defer to decodeJsonFrame's stricter error path below.
            }

            if (parseSucceeded && typeof parsedForBootstrap === 'object'
                && parsedForBootstrap !== null
                && (parsedForBootstrap as { t?: unknown }).t === 'mesh_handshake') {
                if (phase !== 'awaiting') {
                    ws.close(1008, 'mesh_handshake out of order');
                    return;
                }
                if (!isMeshHandshakeFrame(parsedForBootstrap)) {
                    ws.close(1008, 'malformed mesh_handshake');
                    return;
                }
                const material: MeshCentralMaterial = {
                    centralInstanceId: parsedForBootstrap.centralInstanceId,
                    centralApiUrl: parsedForBootstrap.centralApiUrl.replace(/\/+$/, ''),
                    callbackJwt: parsedForBootstrap.meshTunnelJwt,
                    jwtIssuedAt: Math.floor(Date.now() / 1000),
                    jwtExpiresAt: parsedForBootstrap.jwtExpiresAt,
                };
                try {
                    MeshCentralRegistry.getInstance().upsert(material);
                    phase = 'consumed';
                    const centralInstanceId = parsedForBootstrap.centralInstanceId;
                    const jwtExpiresAt = parsedForBootstrap.jwtExpiresAt;
                    void (async () => {
                        try {
                            const { MeshService: MeshSvc } = await import('../services/MeshService');
                            MeshSvc.getInstance().logActivity({
                                source: 'mesh', level: 'info',
                                type: 'mesh_handshake.received',
                                message: `mesh callback bootstrap received from central ${centralInstanceId}`,
                                details: { centralInstanceId, jwtExpiresAt },
                            });
                        } catch { /* best-effort log; bootstrap success path must not depend on it */ }
                    })();
                } catch (err) {
                    console.warn(`[meshProxyTunnel] mesh_handshake persist failed: ${sanitizeForLog((err as Error).message)}`);
                    try { ws.close(1011, 'bootstrap persist failed'); } catch { /* ignore */ }
                }
                return;
            }

            if (phase === 'awaiting') phase = 'past';
            switchboard.handleJsonFrame(decodeJsonFrame(text));
        } catch (err) {
            if (isDebugEnabled()) {
                console.warn('[MeshProxy:diag] malformed frame:', sanitizeForLog((err as Error).message));
            }
        }
    };

    const teardown = (): void => {
        ws.off('message', onMessage);
        if (switchboard) {
            switchboard.cleanup('mesh proxy-tunnel closed');
            switchboard = null;
        }
        if (meshServiceCleanup) {
            meshServiceCleanup();
            meshServiceCleanup = null;
        }
    };

    try {
        switchboard = attachTcpStreamSwitchboard({
            ws,
            resolveTarget: resolveByComposeLabels,
            logLabel: 'MeshProxy',
        });

        // Wire listeners synchronously so any first frame from central
        // reaches onMessage even when the reverse-dialer CAS swap below
        // refuses this bridge. Bootstrap material identifies central for
        // the next peer-initiated callback and must persist independent
        // of whether this particular WS becomes the active bridge.
        ws.on('message', onMessage);
        ws.once('close', teardown);
        ws.once('error', (err) => {
            if (isDebugEnabled()) {
                console.warn('[MeshProxy:diag] ws error:', sanitizeForLog(err.message));
            }
            teardown();
        });

        // Register a reverse dialer so this side's MeshForwarder can dial
        // cross-node aliases via `tcp_open_reverse` over the same WS. The
        // CAS swap refuses to overwrite a dialer that another caller
        // (a concurrent proxy-tunnel upgrade, or a pilot agent in a
        // misconfigured deployment) has already installed.
        const { MeshService } = await import('../services/MeshService');
        const meshService = MeshService.getInstance();
        const localSwitchboard = switchboard;
        const localDialer: SwitchboardReverseDialer = {
            openMeshTcpStream(target) {
                return localSwitchboard.openReverseStream(target);
            },
        };
        const installed = meshService.setReverseDialer(localDialer, null);
        if (!installed) {
            console.warn('[MeshProxy] reverse dialer already installed; rejecting concurrent tunnel');
            // Hold the WS open briefly so any in-flight first frame can
            // land in onMessage before we send the close. Central
            // optionally sends a mesh_handshake as the first frame on
            // Trigger 1 / Trigger 2 dials; that bootstrap material must
            // persist via MeshCentralRegistry regardless of whether this
            // WS becomes the active bridge. The wait resolves as soon as
            // any 'message' arrives (the listener attached above runs
            // synchronously on the event and updates the registry); the
            // timeout bounds the close-latency overhead for refused
            // dials that carry no bootstrap.
            await new Promise<void>((resolve) => {
                const onFirst = (): void => { clearTimeout(t); resolve(); };
                const t = setTimeout(() => { ws.off('message', onFirst); resolve(); }, FIRST_FRAME_WAIT_MS);
                ws.once('message', onFirst);
            });
            try { ws.close(1013, 'reverse dialer already installed'); } catch { /* ignore */ }
            // teardown fires on the 'close' event and runs switchboard.cleanup.
            return;
        }
        // Install central's view of this peer's nodeId so handleAccept
        // dispatches cross-node aliases correctly. Done after setReverseDialer
        // succeeds so a CAS-rejected tunnel does not leak nodeId state.
        //
        // The install persists across bridge lifecycles: the peer's identity
        // in central's namespace is stable for the enrollment, not per-WS.
        // Null-clearing on teardown caused dispatch to fall back to
        // getDefaultNodeId() after idle close, which collides with central's
        // own nodeId for Local and misdispatches cross-fleet traffic to the
        // same-node path. A subsequent install with a different nodeId
        // (e.g. re-enrollment) is detected by the setter's overwrite-warn.
        if (peerNodeId !== null) {
            meshService.setProxyTunnelSelfCentralNodeId(peerNodeId);
        }
        meshServiceCleanup = () => {
            meshService.setReverseDialer(null, localDialer);
        };
    } catch (err) {
        if (isDebugEnabled()) {
            console.warn('[MeshProxy:diag] failed to attach switchboard:', sanitizeForLog((err as Error).message));
        }
        try { ws.close(1011, 'switchboard attach failed'); } catch { /* ignore */ }
        return;
    }
}
